### ISSUE TITLE
Project Planning

### ISSUE THREAD

**Issue by DavidCrockettDJ** [DavidCrockettDJ/ScaryRooms#1]

**Comment by DavidCrockettDJ** [comment]
Initial meeting to discuss project goals and organization.

**Comment by UhhSleep** [comment]
define scope of game

Scope:
3 separate rooms, each a different theme. No set amount of puzzle requirements.

**Comment by DavidCrockettDJ** [comment]
Created kanban board and github repo.

**Comment by DavidCrockettDJ** [comment]
**Assets for room/world creation:**
Modular wooden building
Junker Town/ Post apocalyptic town
Damaged_building
